import { Component, inject } from '@angular/core';
import { ActivatedRoute, Router, RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule, FormBuilder, Validators } from '@angular/forms';
import { Observable, catchError, forkJoin, of } from 'rxjs';
import { AuthService } from './core/services/auth.service';
import { ApiService } from './core/services/api.services';
import { Acceptance, Company, Evaluation, Internship, Student, Supervisor, TaskApproval } from './core/models/entities';
import { StatusBadgeComponent } from './shared/components/status-badge.component';
import { EmptyStateComponent } from './shared/components/empty-state.component';
import { LoadingIndicatorComponent } from './shared/components/loading-indicator.component';
import { PageHeaderComponent } from './shared/components/page-header.component';

@Component({ selector:'app-workspace', standalone:true, imports:[CommonModule,RouterLink,RouterLinkActive,ReactiveFormsModule,FormsModule,StatusBadgeComponent,EmptyStateComponent,LoadingIndicatorComponent,PageHeaderComponent], templateUrl:'./workspace.component.html', styleUrl:'./workspace.component.scss' })
export class WorkspaceComponent {
  private route=inject(ActivatedRoute); private router=inject(Router); private api=inject(ApiService); private auth=inject(AuthService); private fb=inject(FormBuilder);
  role=this.auth.role()!; currentPath=''; items: any[]=[]; loading=false; error=''; notice=''; search=''; showForm=false; editing:any=null;
  dashboardLoading=false; dashboardError=''; dashboardStats={
    first: { label: '', value: '0', note: 'No records available' },
    second: { label: '', value: '0', note: 'No records available' },
    third: { label: '', value: '0', note: 'No records available' },
    fourth: { label: '', value: '0', note: 'No records available' }
  };
  studentForm=this.fb.group({firstName:['',Validators.required],lastName:['',Validators.required],email:['',[Validators.required,Validators.email]],phone:['',[Validators.required,Validators.pattern(/^\d{8}$/)]]});
  internshipForm=this.fb.group({title:['',Validators.required],company:['',Validators.required],description:['',[Validators.required,Validators.minLength(20)]],startDate:['',Validators.required],endDate:['',Validators.required],studentId:[1,Validators.required],status:['ACTIVE',Validators.required]});
  companyForm=this.fb.group({name:['',Validators.required],email:['',[Validators.required,Validators.email]],phone:['',[Validators.required,Validators.pattern(/^\d{8}$/)]],address:['',Validators.required]});
  supervisorForm=this.fb.group({firstName:['',Validators.required],lastName:['',Validators.required],email:['',[Validators.required,Validators.email]],phone:['',[Validators.required,Validators.pattern(/^\d{8}$/)]],companyId:[1,Validators.required]});
  evaluationForm=this.fb.group({internshipId:[1,Validators.required],supervisorId:[1,Validators.required],quality:[10,[Validators.required,Validators.min(0),Validators.max(20)]],punctuality:[10,[Validators.required,Validators.min(0),Validators.max(20)]],communication:[10,[Validators.required,Validators.min(0),Validators.max(20)]],appreciation:[''],remarks:['']});
  acceptanceForm=this.fb.group({internshipId:[1,Validators.required],companyId:[1,Validators.required],status:['PENDING',Validators.required],reason:['']});
  taskForm=this.fb.group({internshipId:[1,Validators.required],supervisorId:[1,Validators.required],taskDescription:['',[Validators.required,Validators.minLength(3)]],status:['PENDING',Validators.required],comment:['']});
  selectedRecord:any=null; detailOpen=false;
  constructor(){this.route.url.subscribe(parts=>{this.currentPath=parts.map(p=>p.path).join('/');this.load();});}
  get title(){const labels:Record<string,string>={dashboard:'Overview',students:'Students',companies:'Companies',supervisors:'Supervisors',internships:'Internships',requests:'Internship requests',documents:'Documents',evaluations:'Evaluations',complaints:'Complaints',reports:'Reports',grades:'Grades',tasks:'Task approvals',journal:'Journal',report:'Internship report','assignment-letter':'Assignment letter',evaluation:'My evaluation',complaint:'Complaints',company:'Company profile'};return labels[this.currentPath.split('/').pop()||'dashboard']||'Overview';}
  get nav(){if(this.role==='ADMIN')return [{label:'Overview',path:'/admin/dashboard',icon:'⌂'},{label:'Students',path:'/admin/students',icon:'◎'},{label:'Companies',path:'/admin/companies',icon:'▣'},{label:'Supervisors',path:'/admin/supervisors',icon:'◉'},{label:'Internships',path:'/admin/internships',icon:'◫'},{label:'Requests',path:'/admin/requests',icon:'↗'},{label:'Documents',path:'/admin/documents',icon:'▤'},{label:'Evaluations',path:'/admin/evaluations',icon:'✦'},{label:'Complaints',path:'/admin/complaints',icon:'!'},{label:'Reports & grades',path:'/admin/reports',icon:'▥'}];if(this.role==='COMPANY')return [{label:'Overview',path:'/company/dashboard',icon:'⌂'},{label:'Internship requests',path:'/company/internships',icon:'↗'},{label:'Supervisors',path:'/company/supervisors',icon:'◉'},{label:'Task approvals',path:'/company/tasks',icon:'✓'},{label:'Evaluations',path:'/company/evaluations',icon:'✦'}];return [{label:'Overview',path:'/student/dashboard',icon:'⌂'},{label:'My internships',path:'/student/internships',icon:'◫'},{label:'Company',path:'/student/company',icon:'▣'},{label:'Supervisor',path:'/student/supervisor',icon:'◉'},{label:'Tasks',path:'/student/tasks',icon:'✓'},{label:'Documents',path:'/student/documents',icon:'▤'},{label:'Journal',path:'/student/journal',icon:'✎'},{label:'Evaluation',path:'/student/evaluation',icon:'✦'}];}
  load(){this.loading=true;this.error='';const p=this.currentPath;if(p.endsWith('dashboard')){this.loadDashboard();return;}if(p.includes('students'))this.api.students.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(p.includes('companies'))this.api.companies.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(p.includes('supervisors'))this.api.supervisors.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(this.isRequestPage())this.api.acceptances.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(p.includes('internships'))this.api.internships.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(p.includes('evaluations'))this.api.evaluations.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(p.includes('tasks'))this.api.tasks.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else if(p.includes('requests'))this.api.acceptances.list().subscribe({next:x=>this.done(x),error:e=>this.fail(e)});else {this.items=[];this.loading=false;}}
  private safeList<T>(request: Observable<T[]>){return request.pipe(catchError(() => of([] as T[])));}
  private loadDashboard(){
    this.dashboardLoading=true;this.dashboardError='';
    if(this.role==='STUDENT'){
      forkJoin({internships:this.safeList(this.api.internships.list()),tasks:this.safeList(this.api.tasks.list()),evaluations:this.safeList(this.api.evaluations.list())}).subscribe(({internships,tasks,evaluations})=>{
        const current=internships.find(item=>['ACTIVE','IN_PROGRESS','ONGOING'].includes(item.status.toUpperCase()));
        this.dashboardStats={first:{label:'Internship status',value:current?.status||'Not found',note:current?.title||'No internship record'},second:{label:'Documents',value:'Not available',note:'No document endpoint exists'},third:{label:'Open tasks',value:String(tasks.filter(item=>item.status==='PENDING').length),note:'From task approval records'},fourth:{label:'Evaluation status',value:evaluations.length?'Recorded':'Not found',note:evaluations.length?'Evaluation records available':'No evaluation record'}};
        this.items=internships;this.dashboardLoading=false;this.loading=false;
      });
      return;
    }
    if(this.role==='COMPANY'){
      forkJoin({acceptances:this.safeList(this.api.acceptances.list()),tasks:this.safeList(this.api.tasks.list()),evaluations:this.safeList(this.api.evaluations.list()),internships:this.safeList(this.api.internships.list())}).subscribe(({acceptances,tasks,evaluations,internships})=>{
        this.dashboardStats={first:{label:'Pending requests',value:String(acceptances.filter(item=>item.status==='PENDING').length),note:'Pending acceptance records'},second:{label:'Accepted internships',value:String(acceptances.filter(item=>item.status==='ACCEPTED').length),note:'Accepted acceptance records'},third:{label:'Task approvals',value:String(tasks.filter(item=>item.status==='PENDING').length),note:'Tasks requiring review'},fourth:{label:'Evaluations',value:String(evaluations.length),note:'Evaluation records available'}};
        this.items=internships;this.dashboardLoading=false;this.loading=false;
      });
      return;
    }
    forkJoin({students:this.safeList(this.api.students.list()),companies:this.safeList(this.api.companies.list()),internships:this.safeList(this.api.internships.list()),acceptances:this.safeList(this.api.acceptances.list())}).subscribe(({students,companies,internships,acceptances})=>{
      this.dashboardStats={first:{label:'Total students',value:String(students.length),note:'Student records'},second:{label:'Total companies',value:String(companies.length),note:'Company records'},third:{label:'Total internships',value:String(internships.length),note:'Internship records'},fourth:{label:'Pending requests',value:String(acceptances.filter(item=>item.status==='PENDING').length),note:'Pending acceptance records'}};
      this.items=internships;this.dashboardLoading=false;this.loading=false;
    });
  }
  done(items:any[]){this.items=items||[];this.loading=false;} fail(e:any){this.loading=false;this.error=e?.status===0?'Gateway unavailable. Start the backend services to load live data.':`Could not load ${this.title.toLowerCase()}. Please try again.`;}
  logout(){this.auth.logout();this.router.navigateByUrl('/login');}
  announceUnavailable(feature: string){this.notice=`${feature} is not available in the current backend.`;setTimeout(()=>this.notice='',3500);}
  get formTitle(){return this.isRequestPage()?'request':this.currentPath.includes('tasks')?'task':this.currentPath.includes('students')?'student':this.currentPath.includes('companies')?'company':this.currentPath.includes('supervisors')?'supervisor':this.currentPath.includes('evaluations')?'evaluation':'internship';}
  openNew(){this.editing=null;this.showForm=true;if(this.isRequestPage())this.acceptanceForm.reset({internshipId:1,companyId:1,status:'PENDING'});else if(this.currentPath.includes('internships'))this.internshipForm.reset({studentId:1,status:'ACTIVE'});else if(this.currentPath.includes('supervisors'))this.supervisorForm.reset({companyId:1});else if(this.currentPath.includes('evaluations'))this.evaluationForm.reset({internshipId:1,supervisorId:1,quality:10,punctuality:10,communication:10});else if(this.currentPath.includes('tasks'))this.taskForm.reset({internshipId:1,supervisorId:1,status:'PENDING'});else this.form.reset();}
  edit(item:any){this.editing=item;this.showForm=true;this.form.patchValue(item);}
  view(item:any){if(!item.id){this.selectedRecord=item;this.detailOpen=true;return;}let request: Observable<any>;if(this.currentPath.includes('students'))request=this.api.students.get(item.id);else if(this.currentPath.includes('companies'))request=this.api.companies.get(item.id);else if(this.currentPath.includes('supervisors'))request=this.api.supervisors.get(item.id);else if(this.isRequestPage())request=this.api.acceptances.get(item.id);else if(this.currentPath.includes('internships'))request=this.api.internships.get(item.id);else if(this.currentPath.includes('evaluations'))request=this.api.evaluations.get(item.id);else if(this.currentPath.includes('tasks'))request=this.api.tasks.get(item.id);else request=of(item);request.subscribe({next:record=>{this.selectedRecord=record;this.detailOpen=true},error:e=>this.fail(e)});}
  get form(){return this.currentPath.includes('students')?this.studentForm:this.currentPath.includes('companies')?this.companyForm:this.currentPath.includes('supervisors')?this.supervisorForm:this.currentPath.includes('evaluations')?this.evaluationForm:this.isRequestPage()?this.acceptanceForm:this.currentPath.includes('tasks')?this.taskForm:this.internshipForm;}
  save(){if(this.form.invalid){this.form.markAllAsTouched();return;}let action: Observable<unknown>;if(this.currentPath.includes('students')) action=this.api.students.save(this.form.value as Student);else if(this.currentPath.includes('companies')) action=this.api.companies.save(this.form.value as Company);else if(this.currentPath.includes('supervisors')) action=this.api.supervisors.save(this.form.value as Supervisor);else if(this.currentPath.includes('evaluations')) action=this.api.evaluations.save(this.form.value as Evaluation);else if(this.isRequestPage()) action=this.api.acceptances.save(this.form.value as Acceptance);else if(this.currentPath.includes('tasks')) action=this.api.tasks.save(this.form.value as TaskApproval);else action=this.api.internships.save(this.form.value as Internship);action.subscribe({next:()=>{this.showForm=false;this.notice=this.editing?'Updated successfully':'Created successfully';this.load();setTimeout(()=>this.notice='',3000)},error:(e: unknown)=>this.fail(e)});}
  updateAcceptance(item: Acceptance, status: Acceptance['status']){const reason=status==='REJECTED'?window.prompt('Reason for refusal',item.reason||'')||item.reason:item.reason;this.api.acceptances.save({...item,status,reason}).subscribe({next:()=>{this.notice=`Request ${status.toLowerCase()}`;this.load()},error:e=>this.fail(e)});}
  updateTask(item: TaskApproval, status: TaskApproval['status']){this.api.tasks.save({...item,status}).subscribe({next:()=>{this.notice=`Task ${status.toLowerCase()}`;this.load()},error:e=>this.fail(e)});}
  remove(item:any){if(!item.id||!confirm('Delete this record?'))return;const action=this.currentPath.includes('students')?this.api.students.remove(item.id):this.currentPath.includes('companies')?this.api.companies.remove(item.id):this.currentPath.includes('supervisors')?this.api.supervisors.remove(item.id):this.currentPath.includes('evaluations')?this.api.evaluations.remove(item.id):this.isRequestPage()?this.api.acceptances.remove(item.id):this.currentPath.includes('tasks')?this.api.tasks.remove(item.id):this.api.internships.remove(item.id);action.subscribe({next:()=>{this.notice='Record deleted';this.load()},error:e=>this.fail(e)});}
  filtered(){const q=this.search.toLowerCase();return this.items.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));}
  isRequestPage(){return this.currentPath.includes('requests')||(this.role==='COMPANY'&&this.currentPath.includes('internships'));}
  canManageTasks(){return this.role==='COMPANY' && this.currentPath.includes('tasks');}
  isDataPage(){return ['students','companies','supervisors','internships','requests','evaluations','tasks'].some(x=>this.currentPath.includes(x));}
}
