sonar.projectKey=internship-platform
sonar.projectName=Internship Management Platform
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.modules=eureka-server,api-gateway,student-service,internship-service,company-service

eureka-server.sonar.projectName=Eureka Server
eureka-server.sonar.sources=src/main/java
eureka-server.sonar.tests=src/test/java
eureka-server.sonar.java.binaries=target/classes

api-gateway.sonar.projectName=API Gateway
api-gateway.sonar.sources=src/main/java
api-gateway.sonar.tests=src/test/java
api-gateway.sonar.java.binaries=target/classes

student-service.sonar.projectName=Student Service
student-service.sonar.sources=src/main/java
student-service.sonar.tests=src/test/java
student-service.sonar.java.binaries=target/classes

internship-service.sonar.projectName=Internship Service
internship-service.sonar.sources=src/main/java
internship-service.sonar.tests=src/test/java
internship-service.sonar.java.binaries=target/classes

company-service.sonar.projectName=Company Service
company-service.sonar.sources=src/main/java
company-service.sonar.tests=src/test/java
company-service.sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8
sonar.java.source=21
