spring.application.name=api-gateway
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.routes[0].id=student-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://student-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/student/**

spring.cloud.gateway.server.webflux.routes[1].id=internship-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://internship-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/internships/**

spring.cloud.gateway.server.webflux.routes[2].id=company-service-companies
spring.cloud.gateway.server.webflux.routes[2].uri=lb://company-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/companies/**

spring.cloud.gateway.server.webflux.routes[3].id=company-service-supervisors
spring.cloud.gateway.server.webflux.routes[3].uri=lb://company-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/supervisors/**

spring.cloud.gateway.server.webflux.routes[4].id=company-service-acceptances
spring.cloud.gateway.server.webflux.routes[4].uri=lb://company-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/acceptances/**

spring.cloud.gateway.server.webflux.routes[5].id=company-service-task-approvals
spring.cloud.gateway.server.webflux.routes[5].uri=lb://company-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/task-approvals/**

spring.cloud.gateway.server.webflux.routes[6].id=company-service-evaluations
spring.cloud.gateway.server.webflux.routes[6].uri=lb://company-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/evaluations/**

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[0]=*